// Render a recorded workflow server-side so the integration proof works without JS.
export function binancePreview(record){
  const p=record.payload;
  const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const value=x=>escape(x);
  return `<section id="binance" class="binance-proof" aria-labelledby="binance-title">
  <div class="section-label"><div><p class="eyebrow">BINANCE / FROM READ TO REPLAY</p><h2 id="binance-title">Real inputs.<br><em>Inspectable consequences.</em></h2></div><p class="lab-intro">The official CLI supplies the price and symbol grids. Statebound turns that recorded snapshot into a separate synthetic experiment, then checks the repaired plan.</p></div>
  <div class="bridge-flow"><article><span class="eyebrow">01 / OBSERVE</span><h3>Read Binance.</h3><p>BNBUSDT public Spot testnet data through the documented Skills Hub / official CLI route.</p><strong>${value(p.mandate.quote.price)} <small>USDT / BNB</small></strong><p>Snapshot: <time>${value(p.provenance.observedAt)}</time><br>${value(p.provenance.version)}</p><a href="/binance-read.json" download>Inspect original response &#8599;</a></article>
  <article><span class="eyebrow">02 / DERIVE</span><h3>Respect the grid.</h3><p>A 15 USDT principal target rounds down to a whole lot. The synthetic fee assumption is 10 bps; the total budget stays 20 USDT.</p><strong>${value(p.mandate.goal)} <small>BNB</small></strong><p>Lot step ${value(p.mandate.filters.step)} BNB<br>Price tick ${value(p.mandate.filters.tick)} USDT</p><a href="/binance-workflow.json" download>Inspect derived model &#8599;</a></article>
  <article><span class="eyebrow">03 / VERIFY</span><h3>Reconcile before retry.</h3><p>The recorded AI repair is rebound to this model, checked again and replayed with fresh or inconclusive lookup evidence.</p><strong>${value(p.traces.find(t=>t.id==='repaired').debit)} <small>USDT / REPAIRED</small></strong><p>Blind retry: ${value(p.traces.find(t=>t.id==='blind').debit)} USDT<br>Inconclusive lookup: still UNRESOLVED</p><a href="https://github.com/tang-vu/statebound/blob/main/docs/BINANCE_WORKFLOW.md">Reproduce this workflow &#8599;</a></article></div>
  <details class="lab-provenance"><summary>What is real, assumed and independently checked</summary><p>Real: the saved public testnet response. Imported: price, tick, lot size and notional bounds. Assumed: fake account, fixed execution price, 10 bps fee and finite IOC fault model. No live AI call, hosted MCP connection or exchange write is claimed.</p><p>Unmapped venue filters: ${value(p.provenance.unmappedFilters.join(', '))}. This is not a venue-valid order recommendation. The original 600 USDT flagship remains a separate fixture.</p><p>Both evidence bundles rerun bounded search and exact replay. Reproduce offline with <code>npm run integration:verify</code>.</p><p class="lab-trace-hash">Workflow manifest: ${value(record.manifest)}</p></details>
  </section>`;
}
