import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {fixture,templateRepair} from '../src/core.js';
import {verify} from '../src/evidence.js';
const base='http://127.0.0.1:4381';
const denied=await fetch(`${base}/api/runs/${randomUUID()}`);assert.equal(denied.status,401);
const session=await fetch(`${base}/api/session`);const cookie=session.headers.get('set-cookie')!.split(';')[0];
const {mandate,plan}=fixture();const input={mandate,plan,action:'check',mode:'baseline'};
const headers={'Content-Type':'application/json','X-Statebound-Action':'operator',Cookie:cookie,'Idempotency-Key':randomUUID()};
const blocked=await fetch(`${base}/api/runs`,{method:'POST',headers:{...headers,Origin:'https://example.com'},body:JSON.stringify(input)});assert.equal(blocked.status,403);
const unapproved=await fetch(`${base}/api/runs`,{method:'POST',headers:{Cookie:cookie,'Content-Type':'application/json'},body:JSON.stringify(input)});assert.equal(unapproved.status,403);
const requests=await Promise.all([1,2].map(()=>fetch(`${base}/api/runs`,{method:'POST',headers,body:JSON.stringify(input)}).then(r=>r.json())));assert.equal(requests[0].id,requests[1].id);
const mismatch=await fetch(`${base}/api/runs`,{method:'POST',headers,body:JSON.stringify({...input,mode:'guarded'})});assert.equal(mismatch.status,400);
let complete=false;
for(let i=0;i<100;i++){const r=await fetch(`${base}/api/runs/${requests[0].id}`,{headers:{Cookie:cookie}}).then(r=>r.json());if(r.status==='FINISHED'){assert.equal(r.result.status,'COUNTEREXAMPLE_FOUND');complete=true;break;}await new Promise(r=>setTimeout(r,100));}assert.ok(complete);
const exported=await fetch(`${base}/api/runs/${requests[0].id}/export`,{headers:{Cookie:cookie}}).then(r=>r.json());assert.equal(verify(exported).verified,true);
const job=await fetch(`${base}/api/runs`,{method:'POST',headers:{...headers,'Idempotency-Key':randomUUID()},body:JSON.stringify({...input,plan:templateRepair(plan),mode:'guarded'})}).then(r=>r.json());
await fetch(`${base}/api/runs/${job.id}/stop`,{method:'POST',headers});const stopped=await fetch(`${base}/api/runs/${job.id}`,{headers:{Cookie:cookie}}).then(r=>r.json());assert.equal(stopped.status,'CANCELLED');
const malformed=await fetch(`${base}/api/runs`,{method:'POST',headers:{...headers,'Idempotency-Key':randomUUID()},body:JSON.stringify({...input,mandate:{...mandate,environment:'mainnet'}})});assert.equal(malformed.status,400);
// Existing idempotency identities are returned even while the worker pool is full.
const pool=await Promise.all([1,2].map(()=>fetch(`${base}/api/runs`,{method:'POST',headers:{...headers,'Idempotency-Key':randomUUID()},body:JSON.stringify({...input,plan:templateRepair(plan),mode:'guarded'})}).then(r=>r.json())));
const retryAtCapacity=await fetch(`${base}/api/runs`,{method:'POST',headers,body:JSON.stringify(input)}).then(r=>r.json());assert.equal(retryAtCapacity.id,requests[0].id);
for(const job of pool)if(job.id)await fetch(`${base}/api/runs/${job.id}/stop`,{method:'POST',headers});
console.log('HTTP gates passed: session, origin, operator action, concurrent idempotency, key mismatch, export, cancellation, mainnet rejection.');
