import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Mandate,Plan} from '../src/core';
import type {Result} from '../src/checker';
import type {Event} from '../src/simulator';
import './style.css';
type Run={id:string;status:string;kind?:string;message?:string;input:{mandate:Mandate;plan:Plan};plan?:Plan;result?:Result;events?:Event[];outcome?:string;provenance?:string};
type Session={fixture:{mandate:Mandate;plan:Plan};integration:{status?:string;route?:string;observedAt?:string;reason?:string;quote?:{price:string;symbol:string}};externalRepair:{output:Plan}|null};
function App(){
  const [session,setSession]=useState<Session|null>(null),[mandate,setMandate]=useState<Mandate|null>(null),[planText,setPlanText]=useState(''),[confirmed,setConfirmed]=useState(false),[run,setRun]=useState<Run|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[phase,setPhase]=useState('Ready to check'),[selected,setSelected]=useState(0),[advanced,setAdvanced]=useState(false),[candidate,setCandidate]=useState(''),[verification,setVerification]=useState('');
  useEffect(()=>{fetch('/api/session').then(r=>r.json()).then((s:Session)=>{setSession(s);setMandate(s.fixture.mandate);setPlanText(JSON.stringify(s.fixture.plan,null,2));const id=location.pathname.match(/\/runs\/([a-f0-9-]+)/)?.[1];if(id)load(id);}).catch(()=>setError('Cannot connect to local server. Start npm run dev.'));},[]);
  async function load(id:string){const r=await fetch(`/api/runs/${id}`);if(!r.ok){setError('Run not found in this local database.');return;}const next:Run=await r.json();setRun(next);setMandate(next.input.mandate);setPlanText(JSON.stringify(next.plan??next.input.plan,null,2));setConfirmed(true);setSelected(Math.max(0,(next.events?.length??1)-1));setBusy(next.status==='RUNNING');if(next.status==='RUNNING')connect(id);}
  function connect(id:string){const events=new EventSource(`/api/runs/${id}/events`);events.onmessage=e=>{const {event}=JSON.parse(e.data);if(event.kind==='progress')setPhase(event.phase);if(['complete','error','cancelled'].includes(event.kind)){events.close();setBusy(false);load(id);}};events.onerror=()=>{events.close();setBusy(false);load(id);};}
  async function normalizedPlan(raw:string,m:Mandate):Promise<Plan>{
    const plan=JSON.parse(raw) as Plan;
    // Server owns canonical hashing. Browser uses the same canonical key order and SHA-256.
    const canonical=(x:unknown):string=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?`[${x.map(canonical).join(',')}]`:`{${Object.entries(x).sort(([a],[b])=>a.localeCompare(b,'en')).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(',')}}`;
    const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(m)));plan.mandateHash=Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('');return plan;
  }
  async function start(action:'check'|'repair'|'replay',mode:'baseline'|'guarded'='baseline',ambiguity=false){
    if(!mandate)return;setError('');setVerification('');
    try {const plan=await normalizedPlan(planText,mandate);let repair:Plan|undefined;
      if(action==='repair'&&candidate.trim())repair=JSON.parse(candidate);
      setBusy(true);setPhase('Starting bounded check');
      const response=await fetch('/api/runs',{method:'POST',headers:{'Content-Type':'application/json','X-Statebound-Action':'operator','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({mandate,plan,action,mode,ambiguity,...(repair?{candidate:repair}:{})})});
      const data=await response.json();if(!response.ok)throw Error(data.error);history.pushState(null,'',`/runs/${data.id}`);setRun({id:data.id,status:'RUNNING',input:{mandate,plan}});connect(data.id);
    }catch(e){setError(e instanceof Error?e.message:'Request failed');setBusy(false);}
  }
  function edit(field:'budget'|'goal'|'feeBps',value:string){if(!mandate)return;setMandate({...mandate,[field]:field==='feeBps'?Number(value):value});setConfirmed(false);setRun(null);}
  const trace=run?.events??[],event=trace[selected],result=run?.result;const repaired=run?.provenance==='template repair'||run?.provenance==='manual'&&run?.plan?.id!==run?.input.plan.id;
  const currentPlan=(()=>{try{return JSON.parse(planText) as Plan;}catch{return null;}})();
  const fail=result?.status==='COUNTEREXAMPLE_FOUND';
  const failureExplanation=trace.length?`${trace.filter(e=>e.effect.kind==='submit').length} submitted attempts produce ${trace.at(-1)?.actualDebit} USDT of concrete debit. ${trace.some(e=>e.observation?.kind==='timeout')?'A lost reply leaves possible execution unresolved. ':''}${trace.some(e=>e.observation?.kind==='balance')?'A stale balance does not release that exposure.':''}`:'';
  const money=(value:string|undefined)=>value??'0';
  if(!mandate||!session)return <main className="loading">Connecting to the local workbench…{error}</main>;
  return <>
    <header><a href="/" className="brand"><span className="brand-mark">S<span>↳</span></span>statebound<span className="version">WORKBENCH / 01</span></a><div className="local"><span className="dot"/> LOCAL SESSION <span className="muted">·</span> SPOT / IOC</div></header>
    <main>
      <div className="intro"><div><div className="eyebrow">EXECUTION UNDER UNCERTAINTY</div><h1>A timeout is not a failed order.</h1><p>Find the path that breaks a mandate. Reconcile the unknown. Check the repair.</p></div><div className="scope"><b>Bounded, inspectable execution</b><span>One symbol. One mandate. Every possible debit counted.</span></div></div>
      <div className="sources"><span><i className="dot amber"/> DATA <b>Synthetic fixture</b></span><span>EXECUTION <b>Simulator</b></span><span>PLANNER <b>{run?.provenance??'Bundled vulnerable fixture'}</b></span><span className="right">MAINNET & TESTNET <b>Unavailable</b></span></div>
      <div className="workspace">
        <aside className="left">
          <section className="panel mandate"><div className="panel-title"><h2><span>01</span> Spending mandate</h2><span className={'badge '+(confirmed?'green':'')}>{confirmed?'CONFIRMED':'DRAFT'}</span></div>
          <div className="pair"><span>Instrument</span><b>{mandate.symbol} <small>BUY · LIMIT IOC</small></b></div>
          <label>Maximum total debit <div className="input-unit"><input aria-label="Maximum total debit" value={mandate.budget} disabled={busy} onChange={e=>edit('budget',e.target.value)}/><span>USDT</span></div></label>
          <label>Net acquisition goal <div className="input-unit"><input aria-label="Net acquisition goal" value={mandate.goal} disabled={busy} onChange={e=>edit('goal',e.target.value)}/><span>BNB</span></div></label>
          <div className="small-grid"><label>Quote fee (bps)<input aria-label="Quote fee" type="number" min="0" max="100" value={mandate.feeBps} disabled={busy} onChange={e=>edit('feeBps',e.target.value)}/></label><div className="reference"><span>Limit price</span><b>{mandate.limitPrice} <small>USDT</small></b></div></div>
          <p className="note">Synthetic price and symbol filters. {mandate.feeBps===0?'Zero-fee arithmetic fixture.':'Quote-denominated fee fixture.'} Not a current Binance quote.</p>
          <button className={confirmed?'confirmed':'primary'} disabled={busy||confirmed} onClick={()=>setConfirmed(true)}>{confirmed?'✓ Mandate confirmed':'Confirm this mandate'}</button>
          <details><summary>Mandate scope & bounds</summary><p className="note">{mandate.maxOrders} orders · {mandate.maxReads} reads · reserve {mandate.reserve} USDT · step {mandate.filters.step} · minimum {mandate.filters.minNotional} USDT. Initial synthetic balance {mandate.initialQuote} USDT. Goal tolerance {mandate.tolerance}. Expires {mandate.expiresAt.slice(0,10)}.</p></details>
          </section>
          <section className="panel"><div className="panel-title"><h2><span>02</span> Execution plan</h2><button className="text-button" onClick={()=>setAdvanced(!advanced)}>{advanced?'Close JSON':'Edit JSON'}</button></div><div className="plan-label">{currentPlan?.id??'Invalid JSON'}</div>
          {advanced?<textarea aria-label="Plan JSON" className="json" value={planText} onChange={e=>{setPlanText(e.target.value);setConfirmed(false);setRun(null);}}/>:<ol className="plan-list">{currentPlan?.nodes.map(n=><li key={n.id} className={(n.op==='query'?'changed ':'')+(event?.node===n.id?'active':'')}><span className="node-icon">{n.op==='submit'?'↑':n.op==='query'?'↻':n.op==='branch'?'⑂':n.op==='complete'?'✓':'·'}</span><div><b>{n.id}</b><small>{n.op==='submit'?`submit ${n.quantity} · bounded IOC`:n.op==='branch'?`${n.guard.field} → ${n.yes} / ${n.no}`:n.op==='query'?'query original attempt':n.op}</small></div></li>)}</ol>}
          <p className="note">{repaired?'Reconciliation branch added. The mandate and search bounds are preserved.':currentPlan?.id==='vulnerable-fixture'?'The bundled plan is deliberately vulnerable. Its retry path is a developer test fixture.':'Typed candidate plan. Each check is bound to this graph and the confirmed mandate.'}</p>{repaired&&<details><summary>Inspect original → repaired control flow</summary><div className="diff"><div><b>Original nodes</b>{run?.input.plan.nodes.map(n=><pre key={n.id}>{JSON.stringify(n,null,2)}</pre>)}</div><div><b>Repaired nodes</b>{run?.plan?.nodes.map(n=><pre key={n.id}>{JSON.stringify(n,null,2)}</pre>)}</div></div></details>}</section>
        </aside>
        <section className="center">
          <div className="panel investigation"><div className="panel-title"><h2><span>03</span> Counterexample lab</h2><span className="badge">{busy?'CHECKING':result?'COMPUTED':'READY'}</span></div>
          <div className="actions"><button className="primary" disabled={!confirmed||busy} onClick={()=>start('check','baseline')}>Find a failure <span>↗</span></button><button disabled={!confirmed||busy} onClick={()=>start('check','guarded')}>Check with guard</button>{busy&&<button onClick={()=>fetch(`/api/runs/${run?.id}/stop`,{method:'POST',headers:{'X-Statebound-Action':'operator'}})}>Cancel check</button>}</div>
          {error&&<div role="alert" className="error">{error}</div>}
          {run?.kind==='error'&&<div role="alert" className="error">{run.message}</div>}
          {run?.status==='CANCELLED'&&<div className="error">Check cancelled. Coverage is incomplete.</div>}
          <div className={'verdict '+(fail?'violation':result?.complete?'safe':'')} aria-live="polite"><span className="verdict-icon">{fail?'!':result?.complete?'✓':'⌁'}</span><div><div className="eyebrow">{busy?phase:fail?'COUNTEREXAMPLE FOUND':result?.status??'WAITING FOR A CHECK'}</div><h3>{busy?'Exploring execution and observation branches…':fail?`${trace.at(-1)?.actualDebit} USDT can leave a ${mandate.budget} USDT mandate.`:result?.complete?'No violation within the checked bound.':'What if the order filled, but the reply never arrived?'}</h3><p>{fail?failureExplanation:result?`${result.reason}. Progress is measured separately.`:'Confirm the mandate and run a fresh search through the supported fault model.'}</p></div></div>
          <div className="metrics"><div><span>Explored states</span><b>{result?.states.toLocaleString()??'—'}</b></div><div><span>Transitions</span><b>{result?.transitions.toLocaleString()??'—'}</b></div><div><span>Search duration</span><b>{result?`${result.durationMs} ms`:'—'}</b></div><div><span>Step bound</span><b>{currentPlan?.maxSteps??'—'}</b></div></div>
          <div className="timeline-title"><h3>Execution trace</h3><span>{trace.length?`${trace.length} computed transitions · select to inspect`:'No events yet'}</span></div>
          <div className="timeline">{trace.length?trace.map((e,i)=><button key={i} className={'timeline-row '+(selected===i?'selected':'')} onClick={()=>setSelected(i)}><span className="step-number">{String(i+1).padStart(2,'0')}</span><span className={'event-mark '+(e.observation?.kind==='timeout'?'amber':'')}>{e.effect.kind==='submit'?'↑':e.effect.kind==='query'?'↻':'·'}</span><span className="event-description"><b>{e.effect.kind==='none'?e.node:e.effect.kind==='submit'?`Submit ${e.effect.quantity} BNB`:e.effect.kind==='query'?'Reconcile original attempt':'Read account balance'}</b><small>{e.observation?.kind==='timeout'?'Delivered: timeout. Execution status unknown.':e.observation?.kind==='balance'?'Delivered: stale initial balance. Exposure remains.':e.observation?.kind==='order'?`Delivered: ${e.observation.status} · ${e.observation.terminal?'terminal':'not decisive'}`:e.observation?.kind==='notFound'?`Not found · ${e.observation.definitive?'complete fixture lookup':'not conclusive'}`:e.reason||'Typed control-flow transition'}</small></span><span className="event-amount">{e.actualDebit}<small>actual USDT</small></span></button>):<div className="empty"><span>⑂</span><h3>A computed path will appear here.</h3><p>Exchange reality and delivered observations are shown separately.<br/>Nothing has been submitted to an exchange.</p></div>}</div>
          </div>
          <section className="panel repair"><div className="panel-title"><h2><span>04</span> Repair & replay</h2><span className="badge">MANDATE PRESERVED</span></div><p>Replace blind retry with a query of the original attempt. Buy only the remaining goal after terminal evidence.</p><div className="actions"><button disabled={!confirmed||busy||!result} onClick={()=>start('repair','guarded')}>Apply template repair</button><button disabled={!confirmed||busy} onClick={()=>start('replay','guarded')}>Replay recoverable case</button><button disabled={!confirmed||busy} onClick={()=>start('replay','guarded',true)}>Replay ambiguity</button></div>
          {run?.outcome&&<p className="outcome">Selected scenario outcome <b>{run.outcome}</b></p>}
          <details><summary>External AI repair · recorded Codex run & new candidates</summary><p className="note">An actual development-session Codex repair is available as a recorded candidate. Loading it does not call a live model. For a fresh AI repair, use the local CLI with your external agent and paste its candidate below.</p><button onClick={async()=>{if(session.externalRepair){const p=await normalizedPlan(JSON.stringify(session.externalRepair.output),mandate);setCandidate(JSON.stringify(p,null,2));}}}>Load recorded Codex candidate</button><textarea className="json" aria-label="Repair candidate JSON" placeholder="Paste full typed candidate plan" value={candidate} onChange={e=>setCandidate(e.target.value)}/><button disabled={!confirmed||busy||!candidate} onClick={()=>start('repair','guarded')}>Validate candidate & recheck</button><p className="note">CLI: npm run plan:repair -- original.json candidate.json</p></details>
          </section>
        </section>
        <aside className="right-column">
          <section className="panel knowledge"><div className="panel-title"><h2>Agent knowledge</h2><span className="badge amber-text">{event?`STEP ${selected+1}`:'NO OBSERVATIONS'}</span></div><div className="exposure"><span>Maximum possible debit</span><b>{money(event?.possibleDebit)} <small>USDT</small></b><div className="bar"><i style={{width:`${Math.min(100,Number(event?.possibleDebit??0)/Number(mandate.budget)*100)}%`}}/></div><small>Against {mandate.budget} USDT confirmed budget</small></div>
          {event?.after.orders.map(o=><div className="belief" key={o.id}><b>{o.id}</b><span className={o.terminal?'green-text':'amber-text'}>{o.terminal?'Terminal evidence':'Possibly executed'}</span><p>{o.states.join(' / ')}</p><div className="pair"><span>Confirmed debit</span><b>{o.debit}</b></div><div className="pair"><span>Additional possible debit</span><b>{(Number(o.terminal?o.debit:o.max)-Number(o.debit)).toFixed(4)}</b></div><div className="pair"><span>Confirmed net quantity</span><b>{o.net}</b></div></div>)}
          {!event&&<p className="note">A missing reply preserves the possible fill. An old balance cannot free that budget.</p>}</section>
          <section className="panel reality"><div className="panel-title"><h2>Exchange reality</h2><span className="badge">REVIEWER ONLY</span></div><div className="pair"><span>Actual cumulative debit</span><b>{money(event?.actualDebit)} USDT</b></div><p className="note">Hidden simulator state. Never passed to the planner or executor.</p>{event?.hiddenEvents.map(o=><div className="hidden-event" key={o.id}>{o.id} · {o.status}<br/>{o.quantity} BNB · fee {o.fee} {o.feeAsset}</div>)}</section>
          <section className="panel integration"><div className="panel-title"><h2>Binance integration</h2></div><span className="badge">{session.integration.status??'UNAVAILABLE'}</span><h3>{session.integration.route??'Official route not connected'}</h3>{session.integration.quote&&<p>{session.integration.quote.symbol} <b>{session.integration.quote.price}</b><br/><small>Recorded official read · {session.integration.observedAt}</small></p>}<p className="note">{session.integration.reason??'Integration data is separate from the synthetic order fixture. Read-only integration does not enable trading.'}</p></section>
          <section className="panel evidence"><h2>Take the evidence with you.</h2><p className="note">Plan, mandate, bounds, observations and integrity hashes. Verify without the UI or an LLM.</p><a className={'button '+(!result?'disabled':'')} href={result?`/api/runs/${run?.id}/export`:undefined} download>Export evidence <span>↓</span></a><button disabled={!result||busy} onClick={async()=>{setVerification('Recomputing in an independent worker…');try{const r=await fetch(`/api/runs/${run?.id}/verify`,{method:'POST',headers:{'X-Statebound-Action':'operator'}});const value=await r.json();setVerification(value.verified?'Verified: replay and bounded search recomputed.':value.error??'Verification failed');}catch{setVerification('Verifier unavailable');}}}>Verify this export</button>{verification&&<p className="note green-text" role="status">{verification}</p>}<code>npm run evidence:verify -- bundle.json</code></section>
        </aside>
      </div>
      <footer><span>STATEBOUND · FINITE MODEL, EXPLICIT LIMITS</span><span>No real orders. No unbounded safety claim. <a href="https://github.com/tang-vu/statebound" target="_blank" rel="noreferrer">Source ↗</a></span></footer>
    </main>
  </>;
}
createRoot(document.getElementById('root')!).render(<App/>);
