import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Mandate,Plan} from '../src/core';
import type {Result} from '../src/checker';
import type {Event} from '../src/simulator';
import {PlanSchema,MandateSchema} from '../src/schema';
import './style.css';
type Run={id:string;status:string;kind?:string;message?:string;input:{mandate:Mandate;plan:Plan};plan?:Plan;result?:Result;events?:Event[];outcome?:string;provenance?:string};
type Session={fixture:{mandate:Mandate;plan:Plan};integration:{status?:string;route?:string;observedAt?:string;reason?:string;quote?:{price:string;symbol:string}};externalRepair:{output:Plan}|null};
function App(){
  const [mobileView,setMobileView]=useState<'define'|'check'|'inspect'>('define');
  const previousMobileView=useRef(mobileView);
  useEffect(()=>{
    if(previousMobileView.current===mobileView)return;
    previousMobileView.current=mobileView;
    if(!window.matchMedia('(max-width:700px)').matches)return;
    const frame=requestAnimationFrame(()=>{document.querySelector<HTMLButtonElement>('.mobile-nav button[aria-pressed=true]')?.focus({preventScroll:true});document.getElementById('workspace')?.scrollIntoView({block:'start',behavior:'instant'});});
    return()=>cancelAnimationFrame(frame);
  },[mobileView]);
  const [verifying,setVerifying]=useState(false);
  const stream=useRef<EventSource|null>(null),loadVersion=useRef(0);
  const [session,setSession]=useState<Session|null>(null),[mandate,setMandate]=useState<Mandate|null>(null),[planText,setPlanText]=useState(''),[confirmed,setConfirmed]=useState(false),[run,setRun]=useState<Run|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[phase,setPhase]=useState('Ready to check'),[selected,setSelected]=useState(0),[advanced,setAdvanced]=useState(false),[candidate,setCandidate]=useState(''),[verification,setVerification]=useState('');
  useEffect(()=>{
    let disposed=false;
    const navigate=()=>{stream.current?.close();loadVersion.current++;setError('');setVerification('');setCandidate('');const id=location.pathname.match(/\/runs\/([a-f0-9-]+)/)?.[1];if(id)void load(id);else{setRun(null);setConfirmed(false);setBusy(false);setMobileView('define');void fetchSession();}};
    async function fetchSession(){try{const r=await fetch('/api/session');if(!r.ok)throw Error('The local server is unavailable.');const s:Session=await r.json();if(disposed)return;setSession(s);setMandate(s.fixture.mandate);setPlanText(JSON.stringify(s.fixture.plan,null,2));const id=location.pathname.match(/\/runs\/([a-f0-9-]+)/)?.[1];if(id)void load(id);}catch{if(!disposed)setError('Cannot connect to the local server. Check that the workbench is running, then retry.');}}
    void fetchSession();window.addEventListener('popstate',navigate);
    return()=>{disposed=true;loadVersion.current++;stream.current?.close();window.removeEventListener('popstate',navigate);};
  },[]);
  async function load(id:string){const version=++loadVersion.current;try{const r=await fetch(`/api/runs/${id}`);if(!r.ok)throw Error(r.status===404?'Run not found in this local database.':'Unable to load this run. Reload to try again.');const next:Run=await r.json();if(version!==loadVersion.current)return;setRun(next);setMandate(next.input.mandate);setPlanText(JSON.stringify(next.plan??next.input.plan,null,2));setConfirmed(true);setSelected(Math.max(0,(next.events?.length??1)-1));setBusy(next.status==='RUNNING');setMobileView('check');if(next.status==='RUNNING')connect(id);}catch(e){if(version===loadVersion.current){setError(e instanceof Error?e.message:'Unable to load run.');setBusy(false);}}}
  function connect(id:string){stream.current?.close();const events=new EventSource(`/api/runs/${id}/events`);stream.current=events;events.onmessage=e=>{setError('');const {event}=JSON.parse(e.data);if(event.kind==='progress')setPhase(event.phase);if(['complete','error','cancelled'].includes(event.kind)){events.close();void load(id);}};events.onerror=()=>setError('Connection interrupted. Reconnecting to your running check…');}
  async function normalizedPlan(raw:string,m:Mandate):Promise<Plan>{
    const parsed=PlanSchema.safeParse(JSON.parse(raw));if(!parsed.success)throw Error('The plan is incomplete. Check the JSON fields and control-flow nodes.');const plan=parsed.data;
    // Server owns canonical hashing. Browser uses the same canonical key order and SHA-256.
    const canonical=(x:unknown):string=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?`[${x.map(canonical).join(',')}]`:`{${Object.entries(x).sort(([a],[b])=>a.localeCompare(b,'en')).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(',')}}`;
    const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical(m)));plan.mandateHash=Array.from(new Uint8Array(digest)).map(x=>x.toString(16).padStart(2,'0')).join('');return plan;
  }
  async function start(action:'check'|'repair'|'replay',mode:'baseline'|'guarded'='baseline',ambiguity=false,useCandidate=false){
    if(!mandate||busy||!confirmed)return;loadVersion.current++;setBusy(true);setError('');setVerification('');setMobileView('check');
    try {const plan=await normalizedPlan(planText,mandate);let repair:Plan|undefined;
      if(action==='repair'&&useCandidate&&candidate.trim())repair=JSON.parse(candidate);
      setBusy(true);setPhase('Starting bounded check');setSelected(0);setRun(null);
      const response=await fetch('/api/runs',{method:'POST',headers:{'Content-Type':'application/json','X-Statebound-Action':'operator','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({mandate,plan,action,mode,ambiguity,...(repair?{candidate:repair}:{})})});
      const data=await response.json();if(!response.ok)throw Error(data.error);history.pushState(null,'',`/runs/${data.id}`);setRun({id:data.id,status:'RUNNING',input:{mandate,plan}});connect(data.id);
    }catch(e){setError(e instanceof Error?e.message:'Request failed');setBusy(false);}
  }
  function edit(field:'budget'|'goal'|'feeBps',value:string){if(!mandate)return;loadVersion.current++;setMandate({...mandate,[field]:field==='feeBps'?Number(value):value});setConfirmed(false);setRun(null);setVerification('');setCandidate('');setError('');}
  const trace=run?.events??[],event=trace[selected],result=run?.result;const repaired=run?.provenance==='template repair'||run?.provenance==='manual'&&run?.plan?.id!==run?.input.plan.id;
  const currentPlan=(()=>{try{const parsed=PlanSchema.safeParse(JSON.parse(planText));return parsed.success?parsed.data:null;}catch{return null;}})();
  const mandateValid=mandate&&MandateSchema.safeParse(mandate).success&&Number(mandate.budget)>0&&Number(mandate.goal)>0;
  const fail=result?.status==='COUNTEREXAMPLE_FOUND';
  const failureExplanation=trace.length?`${trace.filter(e=>e.effect.kind==='submit').length} submitted attempts produce ${trace.at(-1)?.actualDebit} USDT of concrete debit. ${trace.some(e=>e.observation?.kind==='timeout')?'A lost reply leaves possible execution unresolved. ':''}${trace.some(e=>e.observation?.kind==='balance')?'A stale balance does not release that exposure.':''}`:'';
  const money=(value:string|undefined)=>value??'—';
  if(!mandate||!session)return <main className="loading"><div className="eyebrow">STATEBOUND / LOCAL WORKBENCH</div><h1>{error?'Connection unavailable.':'Opening the workbench.'}</h1><p role="status">{error||'Loading your synthetic mandate and execution plan…'}</p>{error&&<button className="primary" onClick={()=>location.reload()}>Retry connection ↗</button>}</main>;
  return <>
    <a className="skip-link" href="#workspace">Skip to workbench</a>
    <header><a href="/" className="brand"><span className="brand-mark" aria-hidden="true">s<span>↳</span></span>statebound<span className="version">EXECUTION RESEARCH / 001</span></a><div className="local"><span className="dot"/> LOCAL SESSION <span className="muted">/</span> SPOT · IOC</div></header>
    <main>
      <div className="intro"><div className="intro-copy"><div className="eyebrow"><span className="index-cross">+</span> EXECUTION UNDER UNCERTAINTY</div><h1>The reply is lost.<br/><em>The risk isn't.</em></h1><p>A timeout is not a failed order. Find the path that breaks a mandate — then prove the repair within its bounds.</p></div><div className="scope" aria-label="An order can fill even when its reply is lost"><div className="scope-caption"><span>FIG. 01 / THE MISSING REPLY</span><span>SIMULATED</span></div><svg viewBox="0 0 440 130" role="img" aria-label="A submitted order branches into a confirmed fill and a lost reply"><path className="diagram-line" d="M35 65 H155 Q195 65 215 40 L245 20 H405"/><path className="diagram-lost" d="M155 65 Q195 65 215 90 L245 110 H405"/><circle className="diagram-start" cx="35" cy="65" r="8"/><circle className="diagram-fill" cx="405" cy="20" r="8"/><path className="diagram-cross" d="m398 103 14 14 m0-14-14 14"/><text x="24" y="93">SUBMIT</text><text x="267" y="10">ORDER FILLED</text><text x="267" y="97">REPLY LOST</text><circle className="diagram-pulse" cx="155" cy="65" r="5"/></svg><div className="scope-bottom"><b>Unknown ≠ unexecuted.</b><span>Every possible debit counts.</span></div></div></div>
      <div className="sources"><span><i className="dot amber"/> DATA <b>Synthetic fixture</b></span><span>EXECUTION <b>Simulator</b></span><span>PLANNER <b>{run?.provenance??'Bundled vulnerable fixture'}</b></span><span className="right">MAINNET & TESTNET <b>Unavailable</b></span></div>
      <div className="workspace-heading" id="workspace" tabIndex={-1}><h2>The workbench</h2><span>01 DEFINE <i>→</i> 02 CHECK <i>→</i> 03 RECONCILE</span></div>
      <nav className="mobile-nav" aria-label="Workbench sections">{(['define','check','inspect'] as const).map((view,i)=><button key={view} aria-pressed={mobileView===view} aria-controls={'view-'+view} onClick={()=>setMobileView(view)}><span>0{i+1}</span>{view==='define'?'Define':view==='check'?'Check & repair':'Inspect'}{view==='check'&&busy&&<i className="working-dot"/>}</button>)}</nav>
      <div className="workspace" data-view={mobileView}>
        <aside className="left" id="view-define">
          <section className="panel mandate"><div className="panel-title"><h2><span>01</span> Spending mandate</h2><span className={'badge '+(confirmed?'green':'')}>{confirmed?'CONFIRMED':'DRAFT'}</span></div>
          <div className="pair"><span>Instrument</span><b>{mandate.symbol} <small>BUY · LIMIT IOC</small></b></div>
          <label>Maximum total debit <div className="input-unit"><input inputMode="decimal" aria-invalid={!mandateValid} aria-label="Maximum total debit" value={mandate.budget} disabled={busy} onChange={e=>edit('budget',e.target.value)}/><span>USDT</span></div></label>
          <label>Net acquisition goal <div className="input-unit"><input inputMode="decimal" aria-invalid={!mandateValid} aria-label="Net acquisition goal" value={mandate.goal} disabled={busy} onChange={e=>edit('goal',e.target.value)}/><span>BNB</span></div></label>
          <div className="small-grid"><label>Quote fee (bps)<input aria-label="Quote fee" type="number" min="0" max="100" value={mandate.feeBps} disabled={busy} onChange={e=>edit('feeBps',e.target.value)}/></label><div className="reference"><span>Limit price</span><b>{mandate.limitPrice} <small>USDT</small></b></div></div>
          <button className={confirmed?'confirmed':'primary'} disabled={busy||confirmed||!mandateValid||!currentPlan} onClick={()=>{setConfirmed(true);setMobileView('check');}}>{confirmed?'✓ Mandate confirmed':'Confirm this mandate'}</button>
          <p className="note">Synthetic price and symbol filters. {mandate.feeBps===0?'Zero-fee arithmetic fixture.':'Quote-denominated fee fixture.'} Not a current Binance quote.</p>
          {!mandateValid&&<p className="field-error" role="alert">Enter positive budget and goal amounts (up to 8 decimals), and a whole-number fee from 0 to 100 bps.</p>}
          <details><summary>Mandate scope & bounds</summary><p className="note">{mandate.maxOrders} orders · {mandate.maxReads} reads · reserve {mandate.reserve} USDT · step {mandate.filters.step} · minimum {mandate.filters.minNotional} USDT. Initial synthetic balance {mandate.initialQuote} USDT. Goal tolerance {mandate.tolerance}. Expires {mandate.expiresAt.slice(0,10)}.</p></details>
          </section>
          <section className="panel"><div className="panel-title"><h2><span>02</span> Execution plan</h2><button className="text-button" aria-expanded={advanced} aria-controls="plan-editor" onClick={()=>setAdvanced(!advanced)}>{advanced?'Close JSON':'Edit JSON'}</button></div><div className="plan-label">{currentPlan?.id??'Invalid JSON'}</div>
          {advanced?<textarea id="plan-editor" disabled={busy} spellCheck={false} aria-invalid={!currentPlan} aria-label="Plan JSON" className="json" value={planText} onChange={e=>{loadVersion.current++;setPlanText(e.target.value);setConfirmed(false);setRun(null);setCandidate('');setVerification('');}}/>:<ol className="plan-list">{currentPlan?.nodes.map(n=><li key={n.id} className={(n.op==='query'?'changed ':'')+(event?.node===n.id?'active':'')}><span className="node-icon">{n.op==='submit'?'↑':n.op==='query'?'↻':n.op==='branch'?'⑂':n.op==='complete'?'✓':'·'}</span><div><b>{n.id}</b><small>{n.op==='submit'?`submit ${n.quantity} · bounded IOC`:n.op==='branch'?`${n.guard.field} → ${n.yes} / ${n.no}`:n.op==='query'?'query original attempt':n.op}</small></div></li>)}</ol>}
          {!currentPlan&&<p className="field-error" role="alert">Invalid plan. Provide a complete typed plan with valid nodes. Your edits are preserved.</p>}<p className="note">{repaired?'Reconciliation branch added. The mandate and search bounds are preserved.':currentPlan?.id==='vulnerable-fixture'?'The bundled plan is deliberately vulnerable. Its retry path is a developer test fixture.':'Typed candidate plan. Each check is bound to this graph and the confirmed mandate.'}</p>{repaired&&<details><summary>Inspect original → repaired control flow</summary><div className="diff"><div><b>Original nodes</b>{run?.input.plan.nodes.map(n=><pre key={n.id}>{JSON.stringify(n,null,2)}</pre>)}</div><div><b>Repaired nodes</b>{run?.plan?.nodes.map(n=><pre key={n.id}>{JSON.stringify(n,null,2)}</pre>)}</div></div></details>}</section>
        </aside>
        <section className="center" id="view-check">
          <div className="panel investigation" aria-busy={busy}><div className="panel-title"><h2><span>03</span> Counterexample lab</h2><span className="badge">{busy?'CHECKING':result?'COMPUTED':'READY'}</span></div>
          <div className="actions"><button className="primary" disabled={!confirmed||busy} onClick={()=>start('check','baseline')}>Find a failure <span>↗</span></button><button disabled={!confirmed||busy} onClick={()=>start('check','guarded')}>Check with guard</button>{busy&&<button onClick={()=>fetch(`/api/runs/${run?.id}/stop`,{method:'POST',headers:{'X-Statebound-Action':'operator'}})}>Cancel check</button>}</div>
          {!confirmed&&<p className="action-hint">Start with 01 — confirm your spending mandate to unlock the check.</p>}
          {error&&<div role="alert" className="error">{error}</div>}
          {run?.kind==='error'&&<div role="alert" className="error">{run.message}</div>}
          {run?.status==='CANCELLED'&&<div className="error">Check cancelled. Coverage is incomplete.</div>}
          <div className={'verdict '+(fail?'violation':result?.complete?'safe':'')} aria-live="polite"><span className="verdict-icon">{fail?'!':result?.complete?'✓':'⌁'}</span><div><div className="eyebrow">{busy?phase:fail?'COUNTEREXAMPLE FOUND':result?.status??'WAITING FOR A CHECK'}</div><h3>{busy?'Exploring execution and observation branches…':fail?`${trace.at(-1)?.actualDebit} USDT can leave a ${mandate.budget} USDT mandate.`:result?.complete?'No violation within the checked bound.':'What if the order filled, but the reply never arrived?'}</h3><p>{fail?failureExplanation:result?`${result.reason}. Progress is measured separately.`:'Confirm the mandate and run a fresh search through the supported fault model.'}</p></div></div>
          <div className="metrics"><div><span>Explored states</span><b>{result?.states.toLocaleString()??'—'}</b></div><div><span>Transitions</span><b>{result?.transitions.toLocaleString()??'—'}</b></div><div><span>Search duration</span><b>{result?`${result.durationMs} ms`:'—'}</b></div><div><span>Step bound</span><b>{currentPlan?.maxSteps??'—'}</b></div></div>
          <div className="timeline-title"><h3>Execution trace</h3><span>{trace.length?`${trace.length} computed transitions · select to inspect`:'No events yet'}</span></div>
          <div className="timeline">{trace.length?trace.map((e,i)=><button key={i} className={'timeline-row '+(selected===i?'selected':'')} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span className="step-number">{String(i+1).padStart(2,'0')}</span><span className={'event-mark '+(e.observation?.kind==='timeout'?'amber':'')}>{e.effect.kind==='submit'?'↑':e.effect.kind==='query'?'↻':'·'}</span><span className="event-description"><b>{e.effect.kind==='none'?e.node:e.effect.kind==='submit'?`Submit ${e.effect.quantity} BNB`:e.effect.kind==='query'?'Reconcile original attempt':'Read account balance'}</b><small>{e.observation?.kind==='timeout'?'Delivered: timeout. Execution status unknown.':e.observation?.kind==='balance'?'Delivered: stale initial balance. Exposure remains.':e.observation?.kind==='order'?`Delivered: ${e.observation.status} · ${e.observation.terminal?'terminal':'not decisive'}`:e.observation?.kind==='notFound'?`Not found · ${e.observation.definitive?'complete fixture lookup':'not conclusive'}`:e.reason||'Typed control-flow transition'}</small></span><span className="event-amount">{e.actualDebit}<small>actual USDT</small></span></button>):<div className="empty"><span>⑂</span><h3>A computed path will appear here.</h3><p>Exchange reality and delivered observations are shown separately.<br/>Nothing has been submitted to an exchange.</p></div>}</div>
          {event&&<button className="mobile-inspect" onClick={()=>setMobileView('inspect')}>Inspect step {String(selected+1).padStart(2,'0')} <span>Knowledge & exchange reality ↗</span></button>}
          </div>
          <section className="panel repair"><div className="panel-title"><h2><span>04</span> Repair & replay</h2><span className="badge">MANDATE PRESERVED</span></div><p>Replace blind retry with a query of the original attempt. Buy only the remaining goal after terminal evidence.</p><div className="actions"><button disabled={!confirmed||busy||!result} onClick={()=>start('repair','guarded')}>Apply template repair</button><button disabled={!confirmed||busy} onClick={()=>start('replay','guarded')}>Replay recoverable case</button><button disabled={!confirmed||busy} onClick={()=>start('replay','guarded',true)}>Replay ambiguity</button></div>
          {run?.outcome&&<p className="outcome">Selected scenario outcome <b>{run.outcome}</b></p>}
          <details><summary>External AI repair · recorded Codex run & new candidates</summary><p className="note">An actual development-session Codex repair is available as a recorded candidate. Loading it does not call a live model. For a fresh AI repair, use the local CLI with your external agent and paste its candidate below.</p><button disabled={busy||!session.externalRepair} onClick={async()=>{if(session.externalRepair){const p=await normalizedPlan(JSON.stringify(session.externalRepair.output),mandate);setCandidate(JSON.stringify(p,null,2));}}}>Load recorded Codex candidate</button><textarea disabled={busy} spellCheck={false} className="json" aria-label="Repair candidate JSON" placeholder="Paste full typed candidate plan" value={candidate} onChange={e=>setCandidate(e.target.value)}/><button disabled={!confirmed||busy||!candidate} onClick={()=>start('repair','guarded',false,true)}>Validate candidate & recheck</button><p className="note">CLI: npm run plan:repair -- original.json candidate.json</p></details>
          </section>
        </section>
        <aside className="right-column" id="view-inspect">
          <section className="panel knowledge"><div className="panel-title"><h2>Agent knowledge</h2><span className="badge amber-text">{event?`STEP ${selected+1}`:'NO OBSERVATIONS'}</span></div><div className="exposure"><span>Maximum possible debit</span><b>{money(event?.possibleDebit)} <small>USDT</small></b><div className="bar"><i style={{width:`${Math.max(0,Math.min(100,Number(event?.possibleDebit??0)/(Number(mandate.budget)||1)*100))}%`}}/></div><small>Against {mandate.budget} USDT {confirmed?'confirmed':'draft'} budget</small></div>
          {event?.after.orders.map(o=><div className="belief" key={o.id}><b>{o.id}</b><span className={o.terminal?'green-text':'amber-text'}>{o.terminal?'Terminal evidence':'Possibly executed'}</span><p>{o.states.join(' / ')}</p><div className="pair"><span>Confirmed debit</span><b>{o.debit}</b></div><div className="pair"><span>Additional possible debit</span><b>{(Number(o.terminal?o.debit:o.max)-Number(o.debit)).toFixed(4)}</b></div><div className="pair"><span>Confirmed net quantity</span><b>{o.net}</b></div></div>)}
          {!event&&<p className="note">A missing reply preserves the possible fill. An old balance cannot free that budget.</p>}</section>
          <section className="panel reality"><div className="panel-title"><h2>Exchange reality</h2><span className="badge">REVIEWER ONLY</span></div><div className="pair"><span>Actual cumulative debit</span><b>{money(event?.actualDebit)} USDT</b></div><p className="note">Hidden simulator state. Never passed to the planner or executor.</p>{event?.hiddenEvents.map(o=><div className="hidden-event" key={o.id}>{o.id} · {o.status}<br/>{o.quantity} BNB · fee {o.fee} {o.feeAsset}</div>)}</section>
          <section className="panel integration"><div className="panel-title"><h2>Binance integration</h2></div><span className="badge">{session.integration.status??'UNAVAILABLE'}</span><h3>{session.integration.route??'Official route not connected'}</h3>{session.integration.quote&&<p>{session.integration.quote.symbol} <b>{session.integration.quote.price}</b><br/><small>Recorded official read · {session.integration.observedAt}</small></p>}<p className="note">{session.integration.reason??'Integration data is separate from the synthetic order fixture. Read-only integration does not enable trading.'}</p></section>
          <section className="panel evidence"><h2>Take the evidence with you.</h2><p className="note">Plan, mandate, bounds, observations and integrity hashes. Verify without the UI or an LLM.</p><a className={'button '+(!result?'disabled':'')} href={result?`/api/runs/${run?.id}/export`:undefined} download>Export evidence <span>↓</span></a><button disabled={!result||busy||verifying} onClick={async()=>{const version=loadVersion.current;setVerifying(true);setVerification('Recomputing in an independent worker…');try{const r=await fetch(`/api/runs/${run?.id}/verify`,{method:'POST',headers:{'X-Statebound-Action':'operator'}});const value=await r.json();if(version===loadVersion.current)setVerification(value.verified?'Verified: replay and bounded search recomputed.':value.error??'Verification failed');}catch{if(version===loadVersion.current)setVerification('Verifier unavailable. Try again.');}finally{setVerifying(false);}}}>{verifying?'Verifying…':'Verify this export'}</button>{verification&&<p className={'note '+(verification.startsWith('Verified:')?'green-text':'')} role="status">{verification}</p>}<code>npm run evidence:verify -- bundle.json</code></section>
        </aside>
      </div>
      <footer><span>STATEBOUND · FINITE MODEL, EXPLICIT LIMITS</span><span>No real orders. No unbounded safety claim. <a href="https://github.com/tang-vu/statebound" target="_blank" rel="noreferrer">Source ↗</a></span></footer>
    </main>
  </>;
}
createRoot(document.getElementById('root')!).render(<App/>);
